//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UbbRentalBike.Resources.Views.Trip {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Index_pl_PL {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index_pl_PL() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("UbbRentalBike.Resources.Views.Trip.Index_pl_PL", typeof(Index_pl_PL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        internal static string Create_new {
            get {
                return ResourceManager.GetString("Create new", resourceCulture);
            }
        }
        
        internal static string Trip_Name {
            get {
                return ResourceManager.GetString("Trip Name", resourceCulture);
            }
        }
        
        internal static string End_Date {
            get {
                return ResourceManager.GetString("End Date", resourceCulture);
            }
        }
        
        internal static string Start_Date {
            get {
                return ResourceManager.GetString("Start Date", resourceCulture);
            }
        }
        
        internal static string Place_of_Departure {
            get {
                return ResourceManager.GetString("Place of Departure", resourceCulture);
            }
        }
        
        internal static string Destination {
            get {
                return ResourceManager.GetString("Destination", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
    }
}
